[package]
name = "httpserver-config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
clap = { workspace = true }

# Future dependencies for Phase 2+
toml = { workspace = true }

[lib]
name = "httpserver_config"
path = "src/lib.rs"
