[package]
name = "httpserver-balancer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"

[lib]
name = "httpserver_balancer"
path = "src/lib.rs"
